version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${ENV_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  application:
    build: .
    image: country-city
    depends_on:
      - postgres
    environment:
      DB_HOST: host.docker.internal
      ENV_DB: ${ENV_DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      IMAGE_SERVER: ${IMAGE_SERVER}
      SECRET_KEY: ${SECRET_KEY}
      API_VERSION: ${API_VERSION}
    ports:
      - "8737:8737"