spring:
  application:
    name: country-city
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: false
    change-log: classpath:changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/test?stringtype=unspecified
    username: postgres
    password: g2310165
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always


server:
  port: 8737
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /openapi/swagger-config
    url: /openapi
  api-docs:
    path: /openapi

image:
  server: https://i.ibb.co/

secrets:
  jwt-key: ecaad53fd5073b6c5f5e588e8c3f1612a13fd4fb29785b8c2f492b19245ab54a

logging:
  level:
    liquibase: DEBUG
    root: INFO
    org.springframework.web: DEBUG

api:
  title: Country-City
  description: country-city-service
  version: 1
  license:
    name: Apache 2.0
    url: http://springdoc.org
  externalDocs:
    description: Country-City Service Documentation